export const CATEGORIES = [
  'Productivity',
  'Creativity',
  'Education',
  'Entertainment',
  'Health',
  'Finance',
  'Marketing',
  'Customer Support',
  'Development',
  'Design',
  'Writing',
  'Research',
  'Personal Assistant',
  'Language Translation',
  'Data Analysis',
  'Social Media',
  'E-commerce',
  'Gaming',
  'Travel',
  'UX/UI',
  'Backend',
  'Frontend',
  'Data',
  'General',
];

export const TYPES = [
  'Instruction',
  'Completion',
  'Chat',
  'Tool',
  'System',
  'Image Generation',
  'Audio Generation',
  'Video Generation',
  'Code Generation',
  'Data Processing',
  'Summarization',
  'Translation',
  'Sentiment Analysis',
  'Named Entity Recognition',
  'Topic Modeling',
  'Question Answering',
  'Text Classification',
  'Speech Recognition',
  'Speech Synthesis',
  'Reinforcement Learning',
  'Anomaly Detection',
  'Predictive Modeling',
  'Clustering',
  'Time Series Analysis',
  'Optimization',
  'Simulation',
  'Recommendation',
  'Forecasting',
  'Image Recognition',
  'Object Detection',
  'Facial Recognition',
  'Pose Estimation',
  'Style Transfer',
  'Image Segmentation',
  '3D Modeling',
  'Augmented Reality',
  'Virtual Reality',
  'Robotics',
  'IoT',
  'Blockchain',
  'Cybersecurity',
  'DevOps',
  'Cloud Computing',
  'Edge Computing',
  'Quantum Computing',
  'Bioinformatics',
  'Healthcare',
  'Finance',
  'Education',
  'Entertainment',
  'Productivity',
  'Creativity',
  'Customer Support',
  'Personal Assistant',
  'Language Translation',
  'Data Analysis',
  'Social Media',
  'E-commerce',
  'Gaming',
  'Travel',
  'Legal',
];